
// Auto-generated by flue (target: node)
import { getPackagedSkills } from 'virtual:flue/packaged-skills';
import { serve } from '@hono/node-server';
import { sqlite } from '@flue/runtime/node';
import {
  Bash,
  InMemoryFs,
  createFlueContext,
  createNodeAgentCoordinator,
  createNodeDispatchQueue,
  bashFactoryToSessionEnv,
  resolveModel,
  configureFlueRuntime,
  createDefaultFlueApp,
  invokeWorkflowAttached,
  invokeDirectAttached,
  generateWorkflowRunId,
} from '@flue/runtime/internal';
import * as handler_hello_world_0 from "/Users/raven/local/raven/flue-conspiracy/src/agents/hello-world.ts";
import * as handler_raven_lead_1 from "/Users/raven/local/raven/flue-conspiracy/src/agents/raven-lead.ts";

import * as channel_telegram_0 from "/Users/raven/local/raven/flue-conspiracy/src/channels/telegram.ts";
import userApp from "/Users/raven/local/raven/flue-conspiracy/src/app.ts";
import userPersistenceAdapter from "/Users/raven/local/raven/flue-conspiracy/src/db.ts";

// ─── Config ─────────────────────────────────────────────────────────────────

const packagedSkills = getPackagedSkills();


function normalizeBuiltModules(agentModules, workflowModules, channelModules = {}) {
  const manifest = { agents: [], workflows: [] };
  const createdAgents = {};
  const dispatchAgentNames = new Map();
  const workflowHandlers = {};
  const localWorkflowHandlers = {};
  const agentRouteMiddleware = {};
  const workflowRouteMiddleware = {};
  const channelHandlers = {};
  for (const [name, mod] of Object.entries(agentModules)) {
    if (!mod.default || mod.default.__flueCreatedAgent !== true || typeof mod.default.initialize !== 'function') throw new Error('[flue] Agent "' + name + '" must default-export createAgent(...).');
    if (mod.route !== undefined && typeof mod.route !== 'function') throw new Error('[flue] Agent "' + name + '" route export must be a callable Hono middleware value.');
    if (mod.description !== undefined && (typeof mod.description !== 'string' || mod.description.trim().length === 0)) throw new Error('[flue] Agent "' + name + '" description export must be a non-empty string.');
    const transports = {};
    if (typeof mod.route === 'function') transports.http = true;
    const entry = { name, transports, created: true };
    if (mod.description !== undefined) entry.description = mod.description;
    manifest.agents.push(entry);
    createdAgents[name] = mod.default;
    const previousDispatchName = dispatchAgentNames.get(mod.default);
    if (previousDispatchName !== undefined) throw new Error('[flue] Agents "' + previousDispatchName + '" and "' + name + '" default-export the same created agent value. Use distinct createAgent(...) values for dispatchable agent modules.');
    dispatchAgentNames.set(mod.default, name);
    if (typeof mod.route === 'function') agentRouteMiddleware[name] = mod.route;
  }

  for (const [name, mod] of Object.entries(workflowModules)) {
    if (typeof mod.run !== 'function') throw new Error('[flue] Workflow "' + name + '" must export a callable run value.');
    if (mod.route !== undefined && typeof mod.route !== 'function') throw new Error('[flue] Workflow "' + name + '" route export must be a callable Hono middleware value.');
    const transports = {};
    if (typeof mod.route === 'function') transports.http = true;
    manifest.workflows.push({ name, transports });
    localWorkflowHandlers[name] = mod.run;
    if (transports.http) workflowHandlers[name] = mod.run;
    if (typeof mod.route === 'function') workflowRouteMiddleware[name] = mod.route;
  }

  for (const [name, mod] of Object.entries(channelModules)) {
    const channel = mod.channel;
    if (!channel || typeof channel !== 'object' || Array.isArray(channel)) throw new Error('[flue] Channel "' + name + '" must export a created channel as the named "channel" binding.');
    if (!Array.isArray(channel.routes) || channel.routes.length === 0) throw new Error('[flue] Channel "' + name + '" must declare at least one route.');
    const routes = {};
    for (const route of channel.routes) {
      if (!route || typeof route !== 'object' || Array.isArray(route)) throw new Error('[flue] Channel "' + name + '" contains an invalid route declaration.');
      if (typeof route.method !== 'string' || !/^[A-Z]+$/.test(route.method)) throw new Error('[flue] Channel "' + name + '" route method must contain only uppercase ASCII letters.');
      if (typeof route.path !== 'string' || route.path.length < 2 || !route.path.startsWith('/') || route.path.startsWith('//') || route.path.includes('?') || route.path.includes('#')) throw new Error('[flue] Channel "' + name + '" route path must be a non-empty absolute suffix without a query or fragment.');
      const segments = route.path.split('/');
      if (segments.some((segment) => segment === '.' || segment === '..')) throw new Error('[flue] Channel "' + name + '" route path must remain beneath its channel namespace.');
      if (typeof route.handler !== 'function') throw new Error('[flue] Channel "' + name + '" route handler must be callable.');
      const key = route.method + ' ' + route.path;
      if (routes[key] !== undefined) throw new Error('[flue] Channel "' + name + '" declares duplicate route "' + key + '".');
      routes[key] = route.handler;
    }
    channelHandlers[name] = routes;
  }

  return { manifest, createdAgents, dispatchAgentNames, workflowHandlers, localWorkflowHandlers, agentRouteMiddleware, workflowRouteMiddleware, channelHandlers };
}


const agentModules = {
  "hello-world": handler_hello_world_0,
  "raven-lead": handler_raven_lead_1,
};
const workflowModules = {

};
const channelModules = {
  "telegram": channel_telegram_0,
};
const normalized = normalizeBuiltModules(agentModules, workflowModules, channelModules);
const { manifest, createdAgents, dispatchAgentNames, workflowHandlers, localWorkflowHandlers, agentRouteMiddleware, workflowRouteMiddleware, channelHandlers } = normalized;

const isLocalMode = process.env.FLUE_MODE === 'local';
const localCliTarget = process.env.FLUE_CLI_TARGET;
const localCliName = process.env.FLUE_CLI_NAME;
const localCliId = process.env.FLUE_CLI_ID;
// IPC mode requires the explicit internal gate set by the Flue CLI in
// addition to the target vars, so user-supplied FLUE_CLI_* values alone
// can never switch a production server into IPC mode.
const isLocalCliMode =
  process.env.FLUE_INTERNAL_CLI_IPC === '1' &&
  (localCliTarget !== undefined || localCliName !== undefined || localCliId !== undefined);
const hasIpcChannel = typeof process.send === 'function';
if (isLocalCliMode && !hasIpcChannel) {
  console.warn('[flue] FLUE_INTERNAL_CLI_IPC is set but no IPC channel was inherited; ignoring it and starting the HTTP server.');
}

// ─── Sandbox Environments ───────────────────────────────────────────────────

/**
 * Create an empty in-memory sandbox (default).
 * Uses InMemoryFs (no real filesystem access) with sensible defaults:
 * cwd = /home/user, /tmp exists, /bin and /usr/bin exist.
 */
async function createDefaultEnv() {
  const fs = new InMemoryFs();
  return bashFactoryToSessionEnv(() => new Bash({
    fs,
    network: { dangerouslyAllowFullInternetAccess: true },
  }));
}

// Custom persistence from db.ts. connect() is awaited once at startup so
// an unreachable or misconfigured database fails at boot, not inside the
// first request.
if (!userPersistenceAdapter || typeof userPersistenceAdapter.connect !== 'function') {
  throw new Error('[flue] db.ts must default-export a PersistenceAdapter with a connect() method.');
}
let executionStore;
let runStore;
let eventStreamStore;
try {
  if (userPersistenceAdapter.migrate) await userPersistenceAdapter.migrate();
  const stores = await userPersistenceAdapter.connect();
  if (!stores || typeof stores !== 'object') {
    throw new Error('connect() must return { executionStore, runStore, eventStreamStore }.');
  }
  ({ executionStore, runStore, eventStreamStore } = stores);
  if (!executionStore || typeof executionStore.sessions?.save !== 'function' || typeof executionStore.submissions?.getSubmission !== 'function') {
    throw new Error('connect() must return an executionStore with sessions and submissions.');
  }
  if (!runStore || typeof runStore.createRun !== 'function' || typeof runStore.listRuns !== 'function') {
    throw new Error('connect() must return a runStore.');
  }
  if (!eventStreamStore || typeof eventStreamStore.appendEvent !== 'function' || typeof eventStreamStore.readEvents !== 'function') {
    throw new Error('connect() must return an eventStreamStore.');
  }
} catch (error) {
  throw new Error('[flue] Failed to initialize persistence from db.ts: ' + (error instanceof Error ? error.message : error), { cause: error });
}
const persistenceAdapter = userPersistenceAdapter;
const agentCoordinator = createNodeAgentCoordinator({
  submissions: executionStore.submissions,
  sessions: executionStore.sessions,
  agents: createdAgents,
  createContext: createContextForRequest,
  eventStreamStore,
});
const dispatchQueue = createNodeDispatchQueue(agentCoordinator);

// Build per-agent durable admission factories so HTTP prompts enter
// the same durable submission lifecycle as dispatches.
const createAdmission = Object.fromEntries(
  Object.keys(createdAgents).map((name) => [
    name,
    (instanceId) => agentCoordinator.createAdmission(name, instanceId),
  ]),
);

function createContextForRequest(id, runId, payload, req, initialEventIndex, dispatchId) {
  return createFlueContext({
    id,
    runId,
    dispatchId,
    payload,
    initialEventIndex,
    env: process.env,
    req,
    agentConfig: { packagedSkills, resolveModel },
    createDefaultEnv,
    defaultStore: executionStore.sessions,
    submissionStore: executionStore.submissions,
  });
}

// ─── Runtime seed ───────────────────────────────────────────────────────────

// Seed the public flue() sub-app with everything it needs to dispatch agent
// requests in-process. Must run before `flue()` handles any request — by
// virtue of being a top-level statement, it executes before `serve(...)`
// below binds the listener. User app.ts files that call `flue()` at top
// level are also fine because Hono routes are lazy: they read this config
// only when a request arrives.
configureFlueRuntime({
  target: 'node',
  devMode: isLocalMode,
  runtimeVersion: "1.0.0-beta.2",
  manifest,
  createAdmission,
  dispatchQueue,
  resolveDispatchAgentName: (agent) => dispatchAgentNames.get(agent),
  workflowHandlers,
  agentRouteMiddleware,
  workflowRouteMiddleware,
  channelHandlers,
  createContext: createContextForRequest,
  runStore,
  eventStreamStore,
});

// Reconcile any interrupted submissions from a previous process.
// This is best-effort on startup — errors are logged but do not block the server.
agentCoordinator.reconcileSubmissions().catch((error) => {
  console.error('[flue] Startup submission reconciliation failed:', error);
});

// ─── App composition ────────────────────────────────────────────────────────

// User-supplied app.ts: their default export owns the entire request
// pipeline. We just verify it exposes a fetch method and pass the
// listener through. flue() is available for them to mount, but the
// composition is theirs to author.
const flueApp = userApp;
if (!flueApp || typeof flueApp.fetch !== 'function') {
  throw new Error(
    '[flue] app.ts default export must be a Hono app or an object with a fetch(request) method.'
  );
}

// ─── Start ──────────────────────────────────────────────────────────────────

function sendLocalMessage(message, done) {
  if (!process.send) throw new Error('[flue] Local CLI execution requires an inherited IPC connection.');
  process.send(message, done);
}

function localRequest() {
  return new Request('https://flue.invalid/_cli', { method: 'POST' });
}

function localErrorMessage(reason, requestId) {
  return { type: 'error', requestId, error: { type: 'invalid_request', message: reason, details: reason } };
}

function failLocalStartup(reason) {
  sendLocalMessage(localErrorMessage(reason), () => process.exit(1));
}

function parseIpcWorkflowMessage(raw) {
  if (!raw || typeof raw !== 'object' || raw.type !== 'invoke' || typeof raw.requestId !== 'string') {
    throw new Error('IPC workflow messages must have type "invoke" and a string requestId.');
  }
  return { type: 'invoke', requestId: raw.requestId, payload: raw.payload === undefined ? {} : raw.payload };
}

function parseIpcAgentMessage(raw) {
  if (!raw || typeof raw !== 'object' || typeof raw.requestId !== 'string') {
    throw new Error('IPC agent messages must have a string requestId.');
  }
  if (raw.type !== 'prompt' || typeof raw.message !== 'string') {
    throw new Error('IPC agent messages must have type "prompt" with a string message.');
  }
  return { type: 'prompt', requestId: raw.requestId, message: raw.message };
}

function ipcErrorMessage(error, requestId, runId) {
  const publicError = error instanceof Error
    ? { type: 'internal_error', message: error.message, details: error.message }
    : { type: 'internal_error', message: String(error), details: String(error) };
  return runId === undefined
    ? { type: 'error', requestId, error: publicError }
    : { type: 'error', requestId, runId, error: publicError };
}

function startLocalWorkflow(name) {
  const handler = localWorkflowHandlers[name];
  if (!handler) {
    failLocalStartup('Unknown workflow: ' + name);
    return;
  }
  let invoked = false;
  sendLocalMessage({ type: 'ready', target: 'workflow', name });
  process.on('message', (raw) => {
    let message;
    try {
      message = parseIpcWorkflowMessage(raw);
      if (invoked) {
        sendLocalMessage(localErrorMessage('Local workflow execution accepts one invocation only.', message.requestId));
        return;
      }
      invoked = true;
    } catch (error) {
      sendLocalMessage(ipcErrorMessage(error));
      return;
    }
    const runId = generateWorkflowRunId();
    sendLocalMessage({ type: 'started', requestId: message.requestId, runId });
    void invokeWorkflowAttached({
      workflowName: name,
      id: runId,
      runId,
      payload: message.payload,
      request: localRequest(),
      handler,
      createContext: createContextForRequest,
      onEvent: (event) => sendLocalMessage({ type: 'event', requestId: message.requestId, runId, event }),
      runStore,
      eventStreamStore,
    }).then(
      (invocation) => sendLocalMessage({ type: 'result', requestId: message.requestId, runId, result: invocation.result ?? null }, () => process.exit(0)),
      (error) => sendLocalMessage(ipcErrorMessage(error, message.requestId, runId), () => process.exit(1)),
    );
  });
}

function startLocalAgent(name, id) {
  if (!id) {
    failLocalStartup('Local agent connection requires an instance id.');
    return;
  }
  if (!createAdmission[name]) {
    failLocalStartup('Unknown agent for admission: ' + name);
    return;
  }
  sendLocalMessage({ type: 'ready', target: 'agent', name, instanceId: id });
  process.on('message', (raw) => {
    let message;
    try {
      message = parseIpcAgentMessage(raw);
    } catch (error) {
      sendLocalMessage(ipcErrorMessage(error));
      return;
    }
    let didStart = false;
    void invokeDirectAttached({
      payload: { message: message.message },
      admitAttachedSubmission: createAdmission[name](id),
      onEvent: (event) => {
        if (!didStart) {
          didStart = true;
          sendLocalMessage({ type: 'started', requestId: message.requestId });
        }
        sendLocalMessage({ type: 'event', requestId: message.requestId, event });
      },
    }).then(
      (result) => sendLocalMessage({ type: 'result', requestId: message.requestId, result: result ?? null }),
      (error) => sendLocalMessage(ipcErrorMessage(error, message.requestId)),
    );
  });
}

if (isLocalCliMode && hasIpcChannel) {
  if (!localCliName || (localCliTarget !== 'workflow' && localCliTarget !== 'agent')) {
    failLocalStartup('Invalid local CLI target configuration.');
  } else if (localCliTarget === 'workflow') {
    startLocalWorkflow(localCliName);
  } else {
    startLocalAgent(localCliName, localCliId);
  }
  process.on('disconnect', async () => {
    await agentCoordinator.shutdown();
    if (persistenceAdapter.close) await persistenceAdapter.close();
    process.exit(0);
  });
} else {
  const port = parseInt(process.env.PORT || '3000', 10);
  const server = serve({
    fetch: (request, env) => flueApp.fetch(request, env),
    port,
    serverOptions: { requestTimeout: 0 },
  });
  console.log('[flue] Server listening on http://localhost:' + port);
  if (isLocalMode) {
    console.log('[flue] Mode: local');
  }
  console.log('[flue] Agents: ' + "hello-world, raven-lead");
  let shuttingDown = false;
  async function stop(signal, exitCode) {
    if (shuttingDown) return;
    shuttingDown = true;
    console.error('[flue] Received ' + signal + ', shutting down...');
    // Backstop: force-exit if any shutdown step stalls past the coordinator's
    // own drain timeout. unref() so the timer never keeps the process alive.
    setTimeout(() => {
      console.error('[flue] Shutdown timed out, exiting.');
      process.exit(exitCode);
    }, 60_000).unref();
    // 1. Drain active submissions (abort at turn boundary, wait with timeout).
    await agentCoordinator.shutdown();
    // 2. Close persistence adapter.
    if (persistenceAdapter.close) await persistenceAdapter.close();
    // 3. Close HTTP server. Destroy open connections (long-poll and SSE
    // readers are held open indefinitely) so close() can settle.
    await new Promise((resolve) => {
      server.close(resolve);
      server.closeAllConnections();
    });
    console.error('[flue] Stopped.');
    process.exit(exitCode);
  }
  process.on('SIGINT', () => { void stop('SIGINT', 130); });
  process.on('SIGTERM', () => { void stop('SIGTERM', 143); });
}
